### ISSUE TITLE
How to set viewport?

### ISSUE THREAD

**Issue by HaiyiMei** [florian-world/VelocityUE4#1]
Great work there! This repo helps me a lot!
I have a question about how to set the whole viewport in `VelocityMaterial` to get optical flow in a new project? I noticed the setting of `PostProcessVolume` should be set like below, but I still can't get the proper image for my viewport and camera. Looking forward to your answer, thanks.
![image](https://user-images.githubusercontent.com/35397764/100089322-764d2b00-2e8c-11eb-9cc9-8cb6a56f2943.png)

PS: Is there a way to save RGB image and optical flow image simultaneously?

**Comment by florian-world** [comment]
Hi Mei,

I'm glad this repository helps you, but please bare in mind that this is not intended as a tutorial or production code, but a minimal sample project to reproduce issues related to this [pull request](https://github.com/EpicGames/UnrealEngine/pull/6933/).

All I did to apply the post process material is setting the post process volume to 'unbounded' and the blending factor to 1.

Directly from the editor I think there is no way to output both simultaneously, however you can export the movie sequence, then turn off the post process material and export RGB. In this context for optical flow .exr 16-bit output can be useful. For custom code it is possible to implement camera actors with 2DSceneCaptureComponent, which can read the the rendered scene output buffers and save it to files. It is possible to apply the post processing materials when needed in that case and render both at the same time with two different instances. Hope this helps somehow.

Cheers,
Florian
